config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :users

  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]

  root 'static_pages#landing_page'

  get 'about'     => 'static_pages#about'

  get 'index'     => 'static_pages#index'

  get 'contact'   => 'static_pages#contact'

  get 'faq'       => 'static_pages#faq'

  post 'static_pages/thank_you'

  post 'payments/create'
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments
  validates :name, presence:true
  validates :price, numericality: { :greater_than => 0}

  def avg_rating
    comments.average(:rating).to_f
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :authorize_admin, only: [:create, :edit, :update, :destroy]
  respond_to :html, :json
  # GET /products
  # GET /products.json
  def index
    if Rails.env.development?
      if params[:q]
        search_term = params[:q]
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      else
        @products = Product.all
      end
    else
      if params[:q]
        search_term = params[:q]
        @products = Product.where("name ilike ?", "%#{search_term}%")
      else
        @products = Product.all
      end
    end
    respond_with @products
  end


  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page =>params[:page], :per_page=>3)
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize! :new, @product
  end

  # GET /products/1/edit
  def edit
    session[:return_to] ||= request.referer
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :success => 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to session.delete(:return_to), :info=>'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_path, :danger=>'Product was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end

    def authorize_admin
      return unless !current_user.admin?
      redirect_to root_path, :alert => "Only admins can create new or update products"
    end
end

app/helpers/products_helper.rb
module ProductsHelper


  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
  <div class="digg-pagination">
    <div class="page-info pull-right">
      <%= page_entries_info @comments, :model => 'comment' %>
    </div>
      <br/>
      <%= will_paginate @comments, class:"pull-right" %>
  </div>
  <div class="product-reviews">
    <% @comments.each do |comment| %>
      <div class="row">
        <hr class="style-two">
        <div class="col-xs-12">
          <p id="commenter"><%= comment.user.first_name %><small><em> <%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
          <div class="rated" data-score="<%= comment.rating %>"%></div>
          <p><%= comment.body %></p>
          <% if signed_in? %>
            <% if comment.user.id == current_user.id || current_user.admin %>
              <%= link_to product_comment_path(@product,comment), method: :delete, data: {confirm:"Are you sure"}, class:"btn btn-danger btn-xs pull-right" do %>
                <span class="glyphicon glyphicon-trash"></span> Delete
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :colour %>
    <%= f.text_field :colour,class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price,class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows:10, cols: 20, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url %>
    <%= f.text_field:image_url, class:"form-control" %>
  </div>
  <div class="actions">
    <% if @product.new_record? %>
      <%= button_tag(type:"submit",class:"btn btn-success button btn-xs") do %>
        <span class="glyphicon glyphicon-pencil"></span> New Entry
      <% end %>
    <% else %>
      <%= button_tag(type:"submit",class:"btn btn-primary button btn-xs") do %>
        <span class="glyphicon glyphicon-wrench"></span> Update Product Details
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<div class="new-comments">
  <% if current_user %>
    <h4>Add a product review:</h4>
    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
      <div class="form-group">
        <%= f.label :body, "Comments:" %>
        <%= f.text_area :body, class:"form-control", rows:"5", required:true %>
        <span class="text-center">
          <div class="form-group">
            <h5>Rate Before You Hit Submit</h5>
            <div class="rating"></div>
          </div>
        </span>
      </div>
      <div class="actions">
        <%= button_tag(type:"submit", class:"btn btn-success btn-md") do %>
          <span class="glyphicon glyphicon-pencil"></span> Submit
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="col-sm-2 col-md-4 product-list">
    <%= link_to product  do%>
      <%= image_tag(product.image_url, data_zoom_image: product.image_url, class:"img-zoom img-responsive") %>
      <h2><%= product.name %></h2>
      <% if product.colour.present? %>
      <h3>Colour:<%= product.colour %></h3>
      <% end %>
      <p><%= simple_format(truncate(product.description, length: 300, omission:'....(continued)')) %></p>
      <div class="price">
        <h3 class="text-center">Price: <%= number_to_currency(product.price) %></h3>
      </div>
      <div class="actions">
        <% if signed_in? && current_user.admin? %>
          <%= link_to product, class:"btn btn-info btn-xs", role:"button" do %>
            <i class="glyphicon glyphicon-eye-open"></i> Show Details
          <% end %> |
          <%= link_to edit_product_path(product), class:"btn btn-warning btn-xs", role:"button" do %>
            <i class="glyphicon glyphicon-wrench"></i> Edit
          <% end %> |
          <%= link_to product, class:"btn btn-danger btn-xs", role:"button", method: :delete, data: { confirm: 'Are you sure?' } do%>
            <i class="glyphicon glyphicon-trash"></i> Trash
          <% end %>
        <% else %>
          <hr class="style-two">
          <%= link_to product, class:"btn btn-info btn-xs", role:"button" do %>
            <i class="glyphicon glyphicon-eye-open"></i> Show Details
          <% end %>
        <% end %>
      </div>
      <hr class="style-two visible-lg">
    <% end %>
</div>

app/views/products/edit.html.erb
<div class="pages">
  <h1>Editing Product</h1>

  <%= render 'form' %>

  <%= link_to @product, class:"btn btn-info btn-xs", role:"button" do %> 
    <i class="glyphicon glyphicon-eye-open"></i> Show
  <% end %> |
  <%= link_to products_path, class:"btn btn-primary btn-xs", role:"button" do %>
    <i class="glyphicon glyphicon-chevron-left"></i> Back
  <% end %>
</div>

app/views/products/index.html.erb
<%= provide(:title, "All Products")%>
<div class="pull-right">
<br/>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to new_product_path, class:"btn btn-primary btn-xs", role:"button" do %>
    <i class="glyphicon glyphicon-plus"></i> Product
  <% end %>
<% end %>
</div>
<div class="container product-container">
  <%= render 'layouts/flash' %>
  <div class="row product-row">
    <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<%= provide(:title, "New Product")%>
<div class="pages">
  <h1>New Product</h1>

  <%= render 'form' %>

  <%= link_to products_path, class: "btn btn-success btn-xs", role:"button" do %>
    <i class="glyphicon glyphicon-chevron-left"></i> Back
  <% end %>
</div>

app/views/products/show.html.erb
  <div class="container">
    <div class="row" data-product-id="<%= @product.id %>">
      <%= render 'layouts/flash' %>
      <div class="page-header">
        <!-- Start of product caching -->

        <h2><strong>Name:</strong><%= @product.name %></h2>
      </div>
      <div class="col-sm-4 product-list">
        <div class="thumbnail">
          <h4><strong>Colour: </strong><%= @product.colour %></h4>
          <%= image_tag(@product.image_url, data_zoom_image:@product.image_url, class:'img-zoom center-block img-responsive') %>
          <div class="caption">
            <div class="price">
              <h4 class="text-center">Price: <%= number_to_currency(@product.price) %></h4>
            </div>
            <div class="payment">
              <%= form_tag("/payments/create", remote: true) do %>
               <%= render partial: "shared/stripe_checkout_button" %>
               <%= hidden_field_tag(:product_id, @product.id) %>
              <% end %>
            </div>
          </div>
        </div>

      </div>
      <div class="col-sm-8">
        <p id="product-rating">Average Rating: <div class="rated" data-score="<%= @product.avg_rating %>"></div></p>
        <%= simple_format(@product.description) %>
        <div class="actions">
          <% if signed_in? && current_user.admin? %>
            <%= link_to edit_product_path(@product), class:"btn btn-warning btn-xs", role:"button" do %>
              <i class="glyphicon glyphicon-wrench"></i> Update
            <% end %>
            <%= link_to products_path, class:"btn btn-primary btn-xs", role:"button" do %>
              <i class="glyphicon glyphicon-chevron-left"></i> Show Full List
            <% end %>
            <%= link_to @product, class:"btn btn-danger btn-xs", role:"button", method: :destroy, data: { confirm: "Are you sure?"} do %>
              <i class="glyphicon glyphicon-trash"></i> Delete
            <% end %>
          <% else %>
            <%= link_to products_path, class:"btn btn-primary btn-xs", role:"button" do %>
            <i class="glyphicon glyphicon-chevron-left"></i> Show Full List
            <% end %>
          <% end %>
        </div>
        <%= render 'new_comment' %>
        <hr class="style-two">
        <div id="cable-flash" class="alert alert-info" style="display:none" role="alert">
          <a href="#" class="close" data-dismiss="alert" aria-label="close"><span class="glyphicon glyphicon-remove-sign"></span></a>
            <p>A new comment was posted!</p>
        </div>
        <%= render 'comments' %>
      </div>
    </div>
  </div>