config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :users

  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]

  root 'static_pages#landing_page'

  get 'about'     => 'static_pages#about'

  get 'index'     => 'static_pages#index'

  get 'contact'   => 'static_pages#contact'

  get 'faq'       => 'static_pages#faq'

  post 'static_pages/thank_you'

  post 'payments/create'
end

app/views/layouts/_deviseflash.html.erb
<div class="container flash">
  <% flash.each do |type, message| %>
    <% if flash[:notice] %>
      <div class="alert alert-info fade-in">
        <button class="close" data-dismiss="alert"><span class="glyphicon glyphicon-remove-sign"></span></button>
        <%= message %>
      </div>
    <% else %>
      <div class="alert alert-danger fade-in">
        <button class="close" data-dismiss="alert"><span class="glyphicon glyphicon-remove-sign"></button>
        <%= message %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_flash.html.erb
<div class="container flash">
  <% flash.each do |key, value| %>
    <div class="fade-in alert alert-<%= key %>">
    <button class="close" data-dismiss="alert"><span class="glyphicon glyphicon-remove-sign"></span></button>
    <%= value %>
    </div>
  <% end %>
  <% yield %>
</div>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
  &copy; 2016 Bike Berlin &#xb7; Demo site only 
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_page_title(yield(:title)) %></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta http-equiv="X-UA-Compatible" content="IE-edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
</head>

app/views/layouts/_nav.html.erb
<nav id="site-navigation" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid site-nav-width">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class:"navbar-brand" do %>
        <i class="glyphicon glyphicon-home"></i> Bike Berlin
      <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= nav_link("Products", products_path) %></li>
        <li><%= nav_link("FAQ", faq_path) %></li>
        <li><%= nav_link("Contact", contact_path) %></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name%><span class="caret"></span></a>
            <ul class="dropdown-menu" style="background-color: black">
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              <li><%= link_to 'Profile', user_path(current_user) %></li>
              <li><%= link_to 'Edit Details',edit_user_registration_path %></li>
              <% if current_user.admin? %>
              <li><%= link_to 'All Members', users_path %></li>
              <% end %>
            </ul>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Members<span class="caret"></span></a>
            <ul class="dropdown-menu" style="background-color: black">
              <li><%=  link_to 'Sign In', new_user_session_path %></li>
              <li><%=  link_to 'Not a member?', new_user_registration_path %></li>
            </ul>
          </li>
        <% end %>
        <li>
          <%= form_tag("/products", method: "get", class:"search-form") do %>
            <%= label_tag(:q, "Search for:") %>
            <%= text_field_tag(:q) %>
            <%= button_tag(type:"submit", class:"btn btn-success btn-xs") do  %>
              <span class="glyphicon glyphicon-search"></span>Submit
            <% end %>
          <% end %>
        </li>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>

<body>
<%= render "layouts/nav" %>

<div class="container-fluid page-wrapper">
  <%= yield %>
</div>

<%= render "layouts/footer" %>
</body>
</html>